### ISSUE TITLE
i'm use ngxMark with formControlName is error

### ISSUE THREAD

**Issue by KanKai** [JsDaddy/ngx-mask#226]
`<input formControlName="totalPaymentMethod" mask="00*.00" [(ngModel)]="numberOrStringFormModel" >`

**Comment by NepipenkoIgor** [comment]
@KanKai Hi. Could you provide error message ?

**Comment by neilhem** [comment]
Bad practice using ngModel with formControlName

**Comment by kosmicke** [comment]
It's happening to me to:
When I use **formControl** it works, but when I use **formControlName** (a form control inside a form group) it throws an error: 

> ngx-mask inputValue.slice is not a function

Please help me. I really like this lib because it's possible to get the 'unmasked' value.

**Comment by kosmicke** [comment]
Updating: The mask works, even though it throws an error after the page is loaded.

First I thought it was because of the matInput but it wasn't. Then I found the cause:

When the value is defined as an object the error occurs:  
` cpf: [{ value: ''}, [Validators.required]],`

![screenshot from 2018-11-30 09-46-16](https://user-images.githubusercontent.com/32934713/49287892-4548e400-f486-11e8-84b8-b76a1cb8272d.png)


But if its a simple value it doesn't cpf: ['', [Validators.required]],
`cpf: ['', [Validators.required]],`
![screenshot from 2018-11-30 09-48-35](https://user-images.githubusercontent.com/32934713/49287904-4b3ec500-f486-11e8-9103-ae8f2f8f0c33.png)

**Comment by Thegrep01** [comment]
@kosmicke can you provide more details about you config and about your form, i did not find this problems

**Comment by Emeritvs** [comment]
@kosmicke Did you solved your issue? I have this same error with a input with 4 mask possibilities, and I'm trying to change the mask after the function loads the data and write inside the input.
